// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJkZXdSpROY0g5ro-4APv08Fd5rHlk8zs',
    appId: '1:554660674974:web:3b69774f2aa1dcf121ea8f',
    messagingSenderId: '554660674974',
    projectId: 'engebaba-2fa21',
    authDomain: 'engebaba-2fa21.firebaseapp.com',
    storageBucket: 'engebaba-2fa21.firebasestorage.app',
    measurementId: 'G-QYND5E6X8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALij0tUKdgjIdf_G4xYjqHAUYu8S69J9s',
    appId: '1:554660674974:android:6773569c66541b6b21ea8f',
    messagingSenderId: '554660674974',
    projectId: 'engebaba-2fa21',
    storageBucket: 'engebaba-2fa21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARz2EFzFdvggSzK9EVz5m5C-xuws83Jys',
    appId: '1:554660674974:ios:492bfd471bb142e121ea8f',
    messagingSenderId: '554660674974',
    projectId: 'engebaba-2fa21',
    storageBucket: 'engebaba-2fa21.firebasestorage.app',
    iosBundleId: 'com.example.reference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARz2EFzFdvggSzK9EVz5m5C-xuws83Jys',
    appId: '1:554660674974:ios:492bfd471bb142e121ea8f',
    messagingSenderId: '554660674974',
    projectId: 'engebaba-2fa21',
    storageBucket: 'engebaba-2fa21.firebasestorage.app',
    iosBundleId: 'com.example.reference',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJkZXdSpROY0g5ro-4APv08Fd5rHlk8zs',
    appId: '1:554660674974:web:e3716247fd91db2c21ea8f',
    messagingSenderId: '554660674974',
    projectId: 'engebaba-2fa21',
    authDomain: 'engebaba-2fa21.firebaseapp.com',
    storageBucket: 'engebaba-2fa21.firebasestorage.app',
    measurementId: 'G-49V8PCQ1KN',
  );
}
