from dotenv import load_dotenv
import os

load_dotenv()

STATIC_SIGN_PATH_TRAIN = os.getenv("STATIC_SIGN_PATH_TRAIN")
DYNAMIC_SIGN_PATH_TRAIN = os.getenv("DYNAMIC_SIGN_PATH_TRAIN")
STATIC_CSV_OUTPUT_TRAIN = os.getenv("STATIC_CSV_OUTPUT_TRAIN")
DYNAMIC_CSV_OUTPUT_TRAIN = os.getenv("DYNAMIC_CSV_OUTPUT_TRAIN")
STATIC_LABEL_PATH_TRAIN = os.getenv("STATIC_LABEL_PATH_TRAIN")
DYNAMIC_LABEL_PATH_TRAIN = os.getenv("DYNAMIC_LABEL_PATH_TRAIN")


STATIC_SIGN_PATH_TEST = os.getenv("STATIC_SIGN_PATH_TEST")
DYNAMIC_SIGN_PATH_TEST = os.getenv("DYNAMIC_SIGN_PATH_TEST")
STATIC_CSV_OUTPUT_TEST = os.getenv("STATIC_CSV_OUTPUT_TEST")
DYNAMIC_CSV_OUTPUT_TEST = os.getenv("DYNAMIC_CSV_OUTPUT_TEST")
STATIC_LABEL_PATH_TEST = os.getenv("STATIC_LABEL_PATH_TEST")
DYNAMIC_LABEL_PATH_TEST = os.getenv("DYNAMIC_LABEL_PATH_TEST")
