name: camera_app
description: A Camera App using CameraAwesome.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  camerawesome:
    path: ../
  path_provider: ^2.1.5
  image: ^4.5.4
  open_filex: ^4.7.0
  meta: ^1.10.0
  rxdart: ^0.28.0
  video_player: ^2.9.2
  dartz: ^0.10.1
  bloc: ^9.0.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  audioplayers: ^6.4.0
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  http: ^1.4.0
  flutter_tts: ^4.2.2
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  exif: ^3.3.0
  flutter_test:
    sdk: flutter
  patrol: ^3.14.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  disable-swift-package-manager: true
  fonts:
    - family: NotoSerifEthiopic
      fonts:
        - asset: assets/fonts/NotoSerifEthiopic-Regular.ttf
        - asset: assets/fonts/NotoSerifEthiopic-Bold.ttf
          weight: 700
        
  assets:
    - assets/models/
    - assets/fonts/
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

# patrol:
#   android:
#     package_name: com.example.camera_app
#   ios:
#     bundle_id:
